//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int Id { get; set; }
        public string PatientId { get; set; }
        public int DoctorScheduleId { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int TypeEventId { get; set; }
        public string Description { get; set; }
    
        public virtual Patients Patients { get; set; }
        public virtual DoctorSchedule DoctorSchedule { get; set; }
        public virtual TypesEvent TypesEvent { get; set; }
    }
}
