//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorSchedule()
        {
            this.Appointments = new HashSet<Appointments>();
        }
    
        public int Id { get; set; }
        public int DoctorId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTimeSchedule { get; set; }
        public System.TimeSpan EndTimeSchedule { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual Doctors Doctors { get; set; }
    }
}
